name: "GitRoll Scan Action"
description:
  "A GitHub Action that requests a GitRoll scan on a specified GitHub user's
  profile"
branding:
  icon: "activity"
  color: "white"
inputs:
  username: # id of input
    description: "The GitHub username to scan"
    required: true
    default: ${{ github.repository_owner }}
  wait: # id of input
    description: "Whether to wait for the scan to complete"
    required: false
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
